let emerald = client.emerald;
emerald.note.clear();
emerald.note.build('\n                             #############\n','seagreen');
emerald.note.build('                  ##############    ##  ##\n','seagreen');
emerald.note.build('            #########            ##    ###\n','seagreen');
emerald.note.build('           ###                ##      ####\n','seagreen');
emerald.note.build('           ## +           ##         ## # \n','seagreen');
emerald.note.build('           ##  #       ##           -#  # \n','seagreen');
emerald.note.build('           ##  ##   #              ###  # \n','seagreen');
emerald.note.build('          ##    ####              ###   # \n','seagreen');
emerald.note.build('          ##    ## ###           ###    # \n','seagreen');
emerald.note.build('          ##   ##   ###         ###    ## \n','seagreen');
emerald.note.build('          ##   #      ###      ###     ## \n','seagreen');
emerald.note.build('         ##   #         ###   ###      ## \n','seagreen');
emerald.note.build('         ##  ##           ######       ## \n','seagreen');
emerald.note.build('         #   #            ######      ##  \n','seagreen');
emerald.note.build('        ##  #        ####     #####   ##  \n','seagreen');
emerald.note.build('        ## #     ####             ######  \n','seagreen');
emerald.note.build('        ###  ###                    ####  \n','seagreen');
emerald.note.build('        ## ##            ############     \n','seagreen');
emerald.note.build('        ###    #############              \n','seagreen');
emerald.note.build('  	#########                         \n','seagreen');
emerald.note.display();
emerald.note.clear();